export const FormMercadoPago = 
'<script>'
    + `var mp = new MercadoPago('{0}');`
    + 'var cardForm = mp.cardForm({'
    + `amount: '{1}',`
    + 'autoMount: true,'
    + '  form: {'
    + '    id: "form-checkout",'
    + '    cardholderName: {'
    + '      id: "form-checkout__cardholderName",'
    + '      placeholder: "Titular do cartão",'
    + '    },'
    + '    cardNumber: {'
    + '      id: "form-checkout__cardNumber",'
    + '      placeholder: "Número do cartão",'
    + '    },'
    + '    cardExpirationDate: {'
    + '      id: "form-checkout__cardExpirationDate",'
    + '      placeholder: "MM/AAAA",'
    + '    },'
    + '    securityCode: {'
    + '      id: "form-checkout__securityCode",'
    + '      placeholder: "CVV",'
    + '    },'
    + '    installments: {'
    + '      id: "form-checkout__installments",'
    + '      placeholder: "Parcelas",'
    + '    },'
    + '    issuer: {'
    + '      id: "form-checkout__issuer",'
    + '      placeholder: "Banco emissor",'
    + '    },'
    + '    identificationType: {'
    + '      id: "form-checkout__identificationType",'
    + '      placeholder: "Tipo de documento",'
    + '    },'
    + '    identificationNumber: {'
    + '      id: "form-checkout__identificationNumber",'
    + '      placeholder: "Número do documento",'
    + '    },'
    + '  },'
    + '  callbacks: {'
    + '    onFormMounted: error => {'
    + '      if (error) return console.warn("Form Mounted handling error: ", error);'
    + '      console.log("Form mounted");'
    + '    },'
    + '    onSubmit: event => {'
    + '      event.preventDefault();'

    + '      const data = {'
    + '        paymentMethodId: payment_method_id,'
    + '        issuerId: issuer_id,'
    + '        amount,'
    + '        token,'
    + '        installments,'
    + '        identificationNumber,'
    + '        identificationType,'
    + '      } = cardForm.getCardFormData();'  

    + '      localStorage.setItem("dadosPagamento", JSON.stringify(data));'
    + '    }'
    + '  }'
    + '});'    
+ '</script>';
